Repository SnakyMz/space-hub, pull requests merged in 2023-08, with the labels that each got.

#26 Feature/basic set up
  README.md
  src/components/Header.js
  src/components/MyProfile.js
Labels: Day 0

#27 Rockets setup
  package-lock.json
  package.json
  src/App.js
  src/components/Rockets.js
  src/index.js
  src/redux/rockets/planet.png
  src/redux/rockets/rocketSlice.js
  src/redux/store.js
Labels: Day 1

#28 Added mission set up, fetched missions, rendered mission list, and filtered into My profile.
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/MissionCard.js
  src/components/Missions.js
  src/components/MyMission.js
  src/components/MyProfile.js
  src/index.css
  src/index.js
  src/redux/missions/missionSlice.js
  src/redux/store.js
Labels: Day 1

#29 Rockets api
  src/components/Missions.js
  src/components/Rocket.js
  src/components/Rockets.js
  src/images/planet.png
  src/redux/rockets/rocketSlice.js
  src/styles/Rockets.css
Labels: Day 1

#30 Added Rockets reservation
  src/components/Header.js
  src/components/MyProfile.js
  src/components/MyRockets.js
  src/components/Rocket.js
  src/components/Rockets.js
  src/index.css
  src/redux/rockets/rocketSlice.js
  src/styles/MyProfile.css
  src/styles/Rockets.css
Labels: Day 1

#32 Adding requirements
  package-lock.json
  package.json
  src/index.css
Labels: Day 1

#33 Added Testing
  src/__tests__/__snapshots__/components.test.js.snap
  src/__tests__/components.test.js
  src/components/Missions.js
  src/components/Rockets.js
  src/components/__mocks__/Header.js
  src/components/__mocks__/Missions.js
  src/components/__mocks__/MyProfile.js
  src/components/__mocks__/Rockets.js
Labels: Day 2

#34 Created the Space Traveler's Hub Web Application.
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/__tests__/RocketSlice.test.js
  src/__tests__/__snapshots__/components.test.js.snap
  src/__tests__/components.test.js
  src/__tests__/missionSlice.test.js
  src/components/Header.js
  src/components/MissionCard.js
  src/components/Missions.js
  src/components/MyMission.js
  src/components/MyProfile.js
  src/components/MyRockets.js
  src/components/Rocket.js
  src/components/Rockets.js
  src/components/__mocks__/Header.js
  src/components/__mocks__/Missions.js
  src/components/__mocks__/MyProfile.js
  src/components/__mocks__/Rockets.js
  src/images/planet.png
  src/index.css
  src/index.js
  src/redux/missions/__mocks__/missionSlice.js
  src/redux/missions/missionSlice.js
  src/redux/rockets/__mocks__/rocketSlice.js
  src/redux/rockets/rocketSlice.js
  src/redux/store.js
  src/styles/MyProfile.css
  src/styles/Rockets.css
Labels: Day 2
